import { Bangers, Nunito } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import { ButtonsProvider } from "./components/ButtonsProvider";
import ScrollToTop from "./components/ScrollToTop";

const bangersFont = Bangers({
  weight: "400",
  variable: "--font-bangers",
  subsets: ["latin"],
});

const nunitoFont = Nunito({
  // weight: '400',
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${bangersFont.variable} ${nunitoFont.variable}`}
    >
      <body>
        <ButtonsProvider>
          <Nav />
          {children}
          <Footer />
        </ButtonsProvider>
        <ScrollToTop />
      </body>
    </html>
  );
}
